export type JobStatus = 'uploading' | 'processing' | 'complete' | 'failed'

export interface Job {
  job_id: string
  status: JobStatus
  current_step: string
  step_detail: string
  input_filename: string
  input_stem: string
  photo_count: number
  created_at: string
  updated_at: string
  error_message: string
  processing_time: number
  output_keys: string[]
  output_urls?: string[]
  debug_urls?: Record<string, string>  // step_name → presigned S3 URL for debug image
  upload_url?: string
  /** 400px-wide JPEG thumbnail of the original input, generated by the load handler.
   *  Returned by both GET /jobs and GET /jobs/{id} so card thumbnails don't need a
   *  separate getJob fetch. */
  thumbnail_url?: string
  /** Client-only: object URL from the uploaded File, used as before-thumbnail placeholder
   *  until thumbnail_url arrives from the backend. */
  preview_url?: string
}

export interface StepUpdate {
  type: 'step_update'
  jobId: string
  status: JobStatus
  step: string
  detail: string
  progress: number
  photoCount: number
}

export interface ApiKeyStatus {
  has_anthropic_key: boolean
  has_openai_key: boolean
}

export interface AuthResponse {
  session_token: string
  user_hash: string
  expires_at: string
}

export interface CreateJobResponse {
  job_id: string
  upload_url: string
  upload_key: string
  expires_in: number
}

export interface JobsResponse {
  jobs: Job[]
  count: number
}

export interface StartJobResponse {
  status: string
  execution_arn: string
}
